runtime: python
env: flex

runtime_config:
    python_version: 3

entrypoint: gunicorn -b :$PORT main:app

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 15

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8

liveness_check:
  check_interval_sec: 300
  timeout_sec: 200
